"""empty message

Revision ID: 1d6431bfb896
Revises: caa051ead8b2
Create Date: 2021-04-13 12:19:31.158190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d6431bfb896'
down_revision = 'caa051ead8b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('Type', sa.String(), nullable=True))
    op.drop_column('questions', 'productType')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('productType', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('questions', 'Type')
    # ### end Alembic commands ###
