"""empty message

Revision ID: caa051ead8b2
Revises: 
Create Date: 2021-04-13 11:47:27.785682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caa051ead8b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('category', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('productType', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'productType')
    op.drop_column('questions', 'category')
    # ### end Alembic commands ###
