"""empty message

Revision ID: e0ad13e797eb
Revises: 0ad8570329f5
Create Date: 2021-04-13 15:44:04.444257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0ad13e797eb'
down_revision = '0ad8570329f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('movies', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('movies', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('questions', 'Type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('questions', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('questions', 'question',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'question',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('questions', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('questions', 'Type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('movies', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('movies', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('categories', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
